// <auto-generated />
using System;
using JobAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobAnalyzer.Migrations
{
    [DbContext(typeof(JobSearchDbContex))]
    [Migration("20260306143936_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("JobAnalyzer.BLL.AIResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("applied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("company")
                        .HasColumnType("longtext");

                    b.Property<string>("coverletter")
                        .HasColumnType("longtext");

                    b.Property<string>("job_requirements")
                        .HasColumnType("longtext");

                    b.Property<string>("jobtitle")
                        .HasColumnType("longtext");

                    b.Property<bool>("matched")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("missing_requirements")
                        .HasColumnType("longtext");

                    b.Property<string>("pre")
                        .HasColumnType("longtext");

                    b.Property<string>("reason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AIResponse");
                });

            modelBuilder.Entity("JobAnalyzer.BLL.JobObject", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("id");

                    b.Property<int>("AIResponseId")
                        .HasColumnType("int");

                    b.Property<bool>("Applied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Applied");

                    b.Property<string>("CompanyLinkedIn")
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("CompanyLinkedIn");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Coverletter")
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("Coverletter");

                    b.Property<byte[]>("DataFileContent")
                        .HasColumnType("blob")
                        .HasColumnName("ResumeFile");

                    b.Property<string>("HTML")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HTMLFileName")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("HtmlJobPostFileContent")
                        .HasColumnType("blob")
                        .HasColumnName("JobFile");

                    b.Property<string>("JobLocation")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobLocation");

                    b.Property<string>("JobPost")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobPost");

                    b.Property<string>("JobPostUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("JobRequirements")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobRequirements");

                    b.Property<string>("JobType")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobType");

                    b.Property<bool>("Matched")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Matched");

                    b.Property<string>("MissingRequirements")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("MissingRequirements");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("SalaryRange");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("When")
                        .HasColumnType("longtext");

                    b.Property<string>("Where")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("AIResponseId");

                    b.ToTable("JobObjects");
                });

            modelBuilder.Entity("JobAnalyzer.BLL.JobObject", b =>
                {
                    b.HasOne("JobAnalyzer.BLL.AIResponse", "AIResponse")
                        .WithMany()
                        .HasForeignKey("AIResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
