// <auto-generated />
using System;
using JobAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobAnalyzer.Migrations
{
    [DbContext(typeof(JobSearchDbContex))]
    [Migration("20260225212522_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("JobAnalyzer.JobObject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Applied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Applied");

                    b.Property<string>("Company")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("company");

                    b.Property<string>("CompanyLinkedIn")
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("CompanyLinkedIn");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Coverletter")
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("Coverletter");

                    b.Property<byte[]>("JobFile")
                        .IsRequired()
                        .HasColumnType("blob")
                        .HasColumnName("JobFile");

                    b.Property<string>("JobPost")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobPost");

                    b.Property<string>("JobRequirements")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("JobRequirements");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<bool>("Matched")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Matched");

                    b.Property<string>("MissingRequirements")
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("MissingRequirements");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ResumeFile")
                        .IsRequired()
                        .HasColumnType("blob")
                        .HasColumnName("ResumeFile");

                    b.HasKey("id");

                    b.ToTable("JobObjects");
                });

            modelBuilder.Entity("JobAnalyzer.Models.Job", b =>
                {
                    b.Property<long>("Postid")
                        .HasColumnType("bigint(10)")
                        .HasColumnName("postid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("varchar(88)")
                        .HasColumnName("company");

                    b.Property<string>("CompanyLinkedin")
                        .IsRequired()
                        .HasMaxLength(119)
                        .HasColumnType("varchar(119)")
                        .HasColumnName("company_linkedin");

                    b.Property<string>("Jobpost")
                        .IsRequired()
                        .HasMaxLength(304)
                        .HasColumnType("varchar(304)")
                        .HasColumnName("jobpost");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("varchar(28)")
                        .HasColumnName("location");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(242)
                        .HasColumnType("varchar(242)")
                        .HasColumnName("logo");

                    b.Property<string>("Postdate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postdate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("varchar(66)")
                        .HasColumnName("title");

                    b.Property<string>("When")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("when");

                    b.HasKey("Postid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Jobpost" }, "jobpost")
                        .IsUnique();

                    b.ToTable("jobs", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("JobAnalyzer.Models.JobProcessed", b =>
                {
                    b.Property<long>("Postid")
                        .HasColumnType("bigint(10)")
                        .HasColumnName("postid");

                    b.Property<bool>("Applied")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("applied");

                    b.Property<DateOnly>("ApplyDate")
                        .HasColumnType("date")
                        .HasColumnName("apply_date");

                    b.Property<bool>("Company")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("company");

                    b.Property<string>("Coverletter")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("coverletter");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("file_id");

                    b.Property<string>("JobRequrirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_requrirements");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("job_title");

                    b.Property<string>("Jobpost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobpost");

                    b.Property<sbyte>("Location")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("location");

                    b.Property<bool>("Matched")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("matched");

                    b.Property<string>("MissingRequirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("missing_requirements");

                    b.Property<DateOnly>("Postdate")
                        .HasColumnType("date")
                        .HasColumnName("postdate");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.HasKey("Postid")
                        .HasName("PRIMARY");

                    b.ToTable("job_processed", (string)null);
                });

            modelBuilder.Entity("JobAnalyzer.Models.JobProcessed", b =>
                {
                    b.HasOne("JobAnalyzer.Models.Job", "Post")
                        .WithOne("JobProcessed")
                        .HasForeignKey("JobAnalyzer.Models.JobProcessed", "Postid")
                        .IsRequired()
                        .HasConstraintName("FK_job_processed_jobs");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JobAnalyzer.Models.Job", b =>
                {
                    b.Navigation("JobProcessed");
                });
#pragma warning restore 612, 618
        }
    }
}
